# Generated by Django 5.2 on 2025-05-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0004_remove_categoria_empresa_remove_producto_empresa_and_more'),
        ('Ventas', '0004_remove_detallepedido_empresa_remove_estado_empresa_and_more'),
        ('accounts', '0005_alter_usuario_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='empresa',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='fecha_de_nacimiento',
            new_name='fecha_expiracion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='genero',
        ),
        migrations.AddField(
            model_name='usuario',
            name='nit_empresa',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombre_empresa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Empresa',
        ),
    ]
