# Generated by Django 5.2 on 2025-05-01 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_usuario_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='plan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
