# Generated by Django 5.2 on 2025-05-08 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_usuario_rol_empleado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='fecha_nacimiento',
            new_name='fecha_contratacion',
        ),
    ]
