# Generated by Django 5.2 on 2025-05-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_fecha_nacimiento_empleado_fecha_contratacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='password',
            field=models.CharField(default=1231, max_length=128),
            preserve_default=False,
        ),
    ]
