# Generated by Django 5.2 on 2025-05-30 18:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_empleado_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('basico', 'Básico'), ('intermedio', 'Intermedio'), ('avanzado', 'Avanzado')], max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion', models.CharField(choices=[('anual', 'Anual')], default='anual', max_length=20)),
                ('max_productos', models.IntegerField(default=0)),
                ('max_empleados', models.IntegerField(default=1)),
                ('max_ventas_mensuales', models.IntegerField(default=0)),
                ('max_sucursales', models.IntegerField(default=1)),
                ('max_clientes', models.IntegerField(default=0)),
                ('tiene_inventario_avanzado', models.BooleanField(default=False)),
                ('tiene_reportes_detallados', models.BooleanField(default=False)),
                ('tiene_multi_sucursal', models.BooleanField(default=False)),
                ('tiene_backup_automatico', models.BooleanField(default=False)),
                ('tiene_api_acceso', models.BooleanField(default=False)),
                ('tiene_soporte_prioritario', models.BooleanField(default=False)),
                ('tiene_integraciones', models.BooleanField(default=False)),
                ('tiene_facturacion_electronica', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'plans',
            },
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_expiracion', models.DateTimeField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada'), ('pendiente', 'Pendiente de Pago'), ('suspendida', 'Suspendida')], default='activa', max_length=20)),
                ('metodo_pago', models.CharField(blank=True, choices=[('tarjeta', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('otro', 'Otro')], max_length=20, null=True)),
                ('monto_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('referencia_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('productos_utilizados', models.IntegerField(default=0)),
                ('empleados_utilizados', models.IntegerField(default=0)),
                ('ventas_mes_actual', models.IntegerField(default=0)),
                ('sucursales_utilizadas', models.IntegerField(default=1)),
                ('clientes_utilizados', models.IntegerField(default=0)),
                ('ultimo_reset_ventas', models.DateField(auto_now_add=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.plan')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='suscripcion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='HistorialSuscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.CharField(blank=True, max_length=255, null=True)),
                ('realizado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('plan_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales_anteriores', to='accounts.plan')),
                ('plan_nuevo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historiales_nuevos', to='accounts.plan')),
                ('suscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='accounts.suscripcion')),
            ],
            options={
                'db_table': 'subscription_history',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
