# Generated by Django 5.1.8 on 2025-06-22 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sucursales", "0001_initial"),
        ("accounts", "0012_plan_suscripcion_historialsuscripcion"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="empleados",
                to="Sucursales.sucursal",
            ),
        ),
    ]
