# Generated by Django 5.1.8 on 2025-06-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0012_plan_suscripcion_historialsuscripcion"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="permisos",
            name="privilegio",
        ),
        migrations.AlterModelOptions(
            name="permisos",
            options={"verbose_name": "Permiso", "verbose_name_plural": "Permisos"},
        ),
        migrations.RemoveField(
            model_name="permisos",
            name="estado",
        ),
        migrations.RemoveField(
            model_name="permisos",
            name="rol",
        ),
        migrations.AddField(
            model_name="permisos",
            name="descripcion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="permisos",
            name="nombre",
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="rol",
            name="permisos",
            field=models.ManyToManyField(
                blank=True, related_name="roles", to="accounts.permisos"
            ),
        ),
        migrations.DeleteModel(
            name="Privilegio",
        ),
    ]
