# Generated by Django 5.2 on 2025-06-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_plan_suscripcion_historialsuscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clave_siat',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_ambiente',
            field=models.CharField(default='2', max_length=2),
        ),
        migrations.AddField(
            model_name='usuario',
            name='codigo_sistema',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono_empresa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
