# Generated by Django 5.2 on 2025-06-22 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_usuario_clave_siat_usuario_codigo_ambiente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nit',
        ),
    ]
