# Generated by Django 5.2 on 2025-06-25 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_empleado_sucursal'),
        ('accounts', '0013_usuario_clave_siat_usuario_codigo_ambiente_and_more'),
    ]

    operations = [
    ]
