# Generated by Django 5.1.8 on 2025-06-04 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0013_remove_permisos_privilegio_alter_permisos_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rol",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emplea",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="empleado",
            name="usuario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles_creados",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
