# Generated by Django 5.1.8 on 2025-06-04 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0014_rol_usuario_alter_empleado_usuario"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="rol",
            name="usuario",
        ),
    ]
