# Generated by Django 5.1.8 on 2025-06-04 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_remove_rol_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="rol",
            name="usuario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emplea",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
