# Generated by Django 5.2 on 2025-04-28 01:03

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipoventa',
            name='estado',
        ),
    ]
