# Generated by Django 5.2 on 2025-04-28 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0002_remove_tipoventa_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='pedido',
            name='tipo_venta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Ventas.tipoventa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
