# Generated by Django 5.2 on 2025-05-01 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0003_remove_factura_venta_remove_pedido_observaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallepedido',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='estado',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='tipoventa',
            name='empresa',
        ),
    ]
