# Generated by Django 5.2 on 2025-05-01 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0005_cliente_pedido_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='cedula_identidad',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='nit',
        ),
    ]
