# Generated by Django 5.2 on 2025-05-02 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0006_remove_cliente_cedula_identidad_remove_cliente_nit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='cliente',
        ),
    ]
