# Generated by Django 5.2 on 2025-05-15 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0011_caja'),
        ('accounts', '0011_empleado_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.empleado'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Ventas.caja'),
        ),
    ]
