# Generated by Django 5.2 on 2025-05-15 22:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0012_caja_empleado_pedido_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='caja',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='Ventas.caja'),
            preserve_default=False,
        ),
    ]
