# Generated by Django 5.2 on 2025-05-15 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0013_alter_pedido_caja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='caja',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Ventas.caja'),
        ),
    ]
