# Generated by Django 5.2 on 2025-05-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0010_cliente_cedula_identidad_cliente_direccion_and_more'),
        ('Ventas', '0015_caja_total_movimiento_efectivo_movimientoefectivo'),
    ]

    operations = [
    ]
