# Generated by Django 5.2 on 2025-06-24 02:04

from django.db import migrations, models
from django.db import connection

def agregar_solo_campos_cliente(apps, schema_editor):
    """
    Agrega ÚNICAMENTE los 3 campos de cliente que realmente faltan
    """
    with connection.cursor() as cursor:
        # Verificar qué campos existen actualmente
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'Ventas_pedido'
            ORDER BY column_name
        """)
        
        columnas_existentes = {row[0].lower() for row in cursor.fetchall()}
        print(f"📋 Columnas existentes en BD: {sorted(columnas_existentes)}")
        
        # SOLO los 3 campos de cliente que realmente faltan
        campos_a_agregar = {
            'cliente_nit': {
                'sql': "ALTER TABLE \"Ventas_pedido\" ADD COLUMN cliente_nit VARCHAR(20) DEFAULT '0' NOT NULL",
                'check': 'cliente_nit'
            },
            'cliente_nombre': {
                'sql': "ALTER TABLE \"Ventas_pedido\" ADD COLUMN cliente_nombre VARCHAR(255) DEFAULT 'SIN NOMBRE' NOT NULL",
                'check': 'cliente_nombre'  
            },
            'cliente_email': {
                'sql': "ALTER TABLE \"Ventas_pedido\" ADD COLUMN cliente_email VARCHAR(254)",
                'check': 'cliente_email'
            }
        }
        
        print("🎯 Agregando solo campos de cliente que faltan...")
        
        for nombre_campo, config in campos_a_agregar.items():
            campo_check = config['check'].lower()
            
            if campo_check not in columnas_existentes:
                print(f"➕ Agregando campo faltante: {nombre_campo}")
                try:
                    cursor.execute(config['sql'])
                    print(f"✅ Campo {nombre_campo} agregado exitosamente")
                except Exception as e:
                    print(f"❌ Error agregando {nombre_campo}: {e}")
                    # No fallar completamente, continuar con los demás
            else:
                print(f"⚠️ Campo {nombre_campo} ya existe, saltando...")
        
        print("🔍 Verificando campos finales...")
        cursor.execute("""
            SELECT column_name 
            FROM information_schema.columns 
            WHERE table_name = 'Ventas_pedido'
            AND column_name IN ('cliente_nit', 'cliente_nombre', 'cliente_email')
            ORDER BY column_name
        """)
        
        campos_cliente_finales = [row[0] for row in cursor.fetchall()]
        print(f"✅ Campos de cliente presentes: {campos_cliente_finales}")

def remover_campos_cliente(apps, schema_editor):
    """
    Función de reversión - remueve los campos de cliente
    """
    with connection.cursor() as cursor:
        campos_a_remover = ['cliente_nit', 'cliente_nombre', 'cliente_email']
        
        for campo in campos_a_remover:
            try:
                cursor.execute(f'ALTER TABLE "Ventas_pedido" DROP COLUMN IF EXISTS {campo}')
                print(f"🗑️ Campo {campo} removido")
            except Exception as e:
                print(f"⚠️ No se pudo remover {campo}: {e}")

class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0016_merge_20250521_0958'),
    ]

    operations = [
        migrations.RunPython(agregar_solo_campos_cliente, remover_campos_cliente),
    ]
