# Generated by Django 5.2 on 2025-06-22 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0016_merge_20250521_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo_recepcion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cuf',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado_factura',
            field=models.CharField(default='Pendiente', max_length=50),
        ),
        migrations.AddField(
            model_name='pedido',
            name='facturado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pedido',
            name='fecha_facturacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
