# Generated by Django 5.1.8 on 2025-06-22 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Sucursales", "0001_initial"),
        ("Ventas", "0016_merge_20250521_0958"),
    ]

    operations = [
        migrations.AddField(
            model_name="caja",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cajas",
                to="Sucursales.sucursal",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clientes",
                to="Sucursales.sucursal",
            ),
        ),
        migrations.AddField(
            model_name="pedido",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pedidos",
                to="Sucursales.sucursal",
            ),
        ),
    ]
