# Generated by Django 5.2 on 2025-06-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0017_pedido_codigo_recepcion_pedido_cuf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_nit',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente_nombre',
            field=models.CharField(default='SIN NOMBRE', max_length=255),
        ),
    ]
