# Generated by Django 5.2 on 2025-06-25 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Ventas', '0017_caja_sucursal_cliente_sucursal_pedido_sucursal'),
        ('Ventas', '0018_pedido_cliente_email_pedido_cliente_nit_and_more'),
    ]

    operations = [
    ]
