version: '3.8'

services:
  db:
    image: postgres:17
    container_name: epunto_venta_db
    restart: always
    environment:
      POSTGRES_DB: PuntoVenta       # Aquí cambiamos el nombre de la base de datos a "PuntoVenta"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mcangel03
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inventario_net

volumes:
  postgres_data:

networks:
  inventario_net:

