# Generated by Django 5.2 on 2025-06-24 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=255)),
                ('tipo_contribuyente', models.CharField(default='PERSONA NATURAL', max_length=50)),
                ('estado', models.CharField(default='ACTIVO', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='nombre_receptor',
            field=models.CharField(default='SIN NOMBRE', max_length=255),
        ),
    ]
