# Generated by Django 5.2 on 2025-05-01 14:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0003_producto_proveedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='empresa',
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Productos.categoria'),
        ),
    ]
