# Generated by Django 5.1.8 on 2025-05-01 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Productos", "0004_alter_producto_categoria"),
        ("Productos", "0004_remove_categoria_empresa_remove_producto_empresa_and_more"),
    ]

    operations = []
