# Generated by Django 5.1.8 on 2025-06-22 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Productos", "0005_categoria_usuario_producto_usuario_proveedor_usuario"),
        ("Sucursales", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="sucursal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="productos",
                to="Sucursales.sucursal",
            ),
        ),
    ]
