# Generated by Django 5.1.8 on 2025-05-01 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Productos", "0005_categoria_usuario_producto_usuario_proveedor_usuario"),
        ("Productos", "0005_merge_20250501_1232"),
    ]

    operations = []
