# Generated by Django 5.2 on 2025-06-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0007_proveedor_correo_proveedor_telefono_pedidoproveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoproveedor',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('recibido', 'Recibido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='precio_compra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
