# Generated by Django 5.2 on 2025-06-26 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0008_pedidoproveedor_estado_pedidoproveedor_precio_compra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidoproveedor',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedor',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='pedidoproveedor',
            name='producto',
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='codigo_control',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='fecha_entrega_estimada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='numero_autorizacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedidoproveedor',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12),
        ),
        migrations.CreateModel(
            name='DetallePedidoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='Productos.pedidoproveedor')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Productos.producto')),
            ],
        ),
    ]
