# Generated by Django 5.2 on 2025-05-05 03:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True)),
                ('clave', models.CharField(max_length=50)),
                ('codigo_ambiente', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cufd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('codigo_control', models.CharField(max_length=30)),
                ('fecha_vigencia', models.DateTimeField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cuis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.cuis')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuf', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nit_emisor', models.CharField(max_length=20)),
                ('nit_receptor', models.CharField(max_length=20)),
                ('fecha_emision', models.DateTimeField()),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('codigo_establecimiento', models.CharField(max_length=10)),
                ('codigo_punto_venta', models.CharField(max_length=10)),
                ('forma_pago', models.CharField(max_length=20)),
                ('estado', models.CharField(default='Aceptado', max_length=20)),
                ('cufd', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.cufd')),
                ('cuis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='facturacion.cuis')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('impuesto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='facturacion.factura')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='cuis',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturacion.usuario'),
        ),
    ]
